### ISSUE TITLE
Some errors in the console, I attach them

### ISSUE THREAD

**Issue by Neinndall** [Fabien2S/DBDToolbox#6]
![erorr 2](https://user-images.githubusercontent.com/66384195/135169312-36034523-ddbd-494c-a55c-0ec63899d23f.JPG)
![error](https://user-images.githubusercontent.com/66384195/135169313-5360458f-49b8-4d74-8746-e133f4a5b101.JPG)

I do not know what they refer to or the conversion of a file has failed, but I am attaching them so you can look at it!
Perhaps other errors originate!

**Comment by Fabien2S** [comment]
Thanks for the report!

I saw them when I tested the tool but did not take the time to investigate, because I saw almost every files exporting successfully

The error is tied to the convertion of the file in .ogg, so, either:
- some sounds files are not exported (If anyody cant find a specific file, please tell me)
- my code is trying to convert files that does not exists (I'm thinking this one is the culprit)

I don't really have time to debug this right now, but you can ignore thoses errors (Expect if you can't find a specific sound, but I doubt it will be related to this)

**Comment by Th3Nigh7mare** [comment]
I do not know, but perhaps being the PTB of patch 5.3.0 there are some files that it is difficult to identify.

**Comment by Neinndall** [comment]
I was doing a test, and a "warn" came out at times. I do not know if it will be something important, but I think that any information about its operation will help you improve it!
![warn_bug](https://user-images.githubusercontent.com/66384195/135734251-2c937aae-6b84-430a-a117-211d75f39d1c.JPG)
s.

**Comment by Fabien2S** [comment]
I known exactly why it did that, and it's nothing to worry about!

When I read the sound files from the game, I don't bother with parsing the extra data about sound properties, and I also print a warning when not reading the whole file, that's it

So this is working as intended, even if not intuitive
